#!/bin/bash
set -e

# Remove old images
rm *.jpg

# Download random images
for i in {1..10}
do
    curl -L https://source.unsplash.com/random/?sig=$i -o image-random-$i.jpg
done

# Download square images
for j in {1..10}
do
    curl -L https://source.unsplash.com/random/800x800/?sig=$j -o image-square-$j.jpg
done

# Download rectangle images
for k in {1..10}
do
    curl -L https://source.unsplash.com/random/800x400/?sig=$k -o image-rect-$k.jpg
done

# Download people images
for l in {1..10}
do
    curl -L https://source.unsplash.com/random/200x200/?people\&sig=$l -o image-people-$l.jpg
done

