name: build-pack

on: 
  push:
  schedule:
    - cron: "21 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install webp fish
        
    - name: Build zip
      run: fish place-images.fish
      
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./pack-place-images.zip
        asset_name: pack-place-images.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Daily build"


