name: build-pack

on: 
  push:
  schedule:
    - cron: "21 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install webp fish
      

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/README.md
        asset_name: README.md
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"


